server:
  port: 8761 #当前 Eureka Server 服务端口。
spring:
  application:
    name: registerCenter
eureka:
  client:
    register-with-eureka: true #是否将当前 Eureka Server 服务作为客户端进行注册。
    fetch-registry: true #是否获取其他 Eureka Server 服务的数据。如果是注册中心集成那么需要true
    service-url:
      defaultZone: http://localhost:8761/eureka/,http://localhost:8762/eureka/,http://localhost:8763/eureka/  #注册中心的访问地址。如果是集成，中间以逗号相隔